arch: amd64
os: linux
language: cpp
dist: bionic

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ["g++-8", "libaio-dev"]
      env:
        - CXX_COMPILER=g++-8
        - C_COMPILER=gcc-8

    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ["g++-9", "libaio-dev"]
      env:
        - CXX_COMPILER=g++-9
        - C_COMPILER=gcc-9

    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ["g++-10", "libaio-dev"]
      env:
        - CXX_COMPILER=g++-10
        - C_COMPILER=gcc-10

    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ["g++-9", "clang-8", "libaio-dev"]
      env:
        - CXX_COMPILER=clang++-8
        - C_COMPILER=clang-8

    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ["g++-9", "clang-9", "libaio-dev"]
      env:
        - CXX_COMPILER=clang++-9
        - C_COMPILER=clang-9

    - os: linux
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: ["g++-9", "clang-10", "libaio-dev"]
      env:
        - CXX_COMPILER=clang++-10
        - C_COMPILER=clang-10

install:
  - pushd ${HOME}
  - mkdir deps
  - cd deps
  - |
    CMAKE_URL="https://cmake.org/files/v3.20/cmake-3.20.0-linux-x86_64.tar.gz"
    mkdir cmake
    travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${HOME}/deps/cmake/bin:${PATH}
  - popd
  - cmake --version

script: >
    cmake -B ${HOME}/build
    -DCMAKE_CXX_COMPILER=$CXX_COMPILER
    -DCMAKE_C_COMPILER=$C_COMPILER
    -DCMAKE_BUILD_TYPE=Release
    -DRAPIDOBJ_BuildTools=ON
    -DRAPIDOBJ_BuildTests=ON
    -DRAPIDOBJ_BuildExamples=ON .
    &&
    cmake --build ${HOME}/build
