name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        build-type: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest

      - name: Install libaio
        if: runner.os == 'Linux'
        run: sudo apt install -y libaio-dev
      
      - name: Configure
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
          -DRAPIDOBJ_BuildTools=ON
          -DRAPIDOBJ_BuildTests=ON
          -DRAPIDOBJ_BuildExamples=ON .

      - name: Build
        run: cmake --build ${{ github.workspace }}/build
 